#! /bin/bash

# declaring variables
name='Halee Tisler'
email='haleetisler@gmail.com'
linkedIn='linkedin.com/in/halee-tisler/'
gitHub='github.com/halee-t'

# printing contact info

echo "Name: $name"
echo "Email: $email"
echo "LinkedIn: $linkedIn"
echo "github: $gitHub"

